### ISSUE TITLE
Support for Orlando, FL

### ISSUE THREAD

**Issue by flyinactor91** [codeforamerica/citygram#184]
My group at CFOrlando's hackathon yesterday started working on adding support for Orlando, FL into Citygram. We have a copy working locally with an empty db, but we'd like to have an example entry for "publishers" and "http_requests". We're already 80% finished with the intermediary server with our first two potential services. Eventually, we'd like to integrate with the main db. Our dev fork is at http://github.com/cforlando/citygram

**Comment by bigfleet** [comment]
Great questions, as publisher is really central to the proceedings.  Would you like to see just a documented structure or something more like a fixture or factory?

Http request is not really something you have to worry about, I'd say.  If I'm wrong, please correct me.

**Comment by flyinactor91** [comment]
If the documented structure contains more info than that in db/schema.sql, yes a more thorough discussion would be helpful. We were under the impression that publisher represented the city which pointed to request/service objects. I’d then assume that publisher is the item that represents each service and the list of supported cities is inferred from these entries?

**Comment by bigfleet** [comment]
Howdy, Orlando!

I've reviewed your code and have a few notes.

I won't be merging anything like police-dispatch-calls.json.

I will absolutely take these icons!  Cool.

I'm not sure what I'm looking at in terms of this intermediary PHP and Python.

It looks like orlando.rb is very close to readiness for inclusion in [citygram/citygram-services](http://github.com/citygram/citygram-services) as it is.  You may find it helpful to check that project out, as it may supply some of the things that you were using PHP/Python to accomplish?  (?)

Publisher does represent a dataset (a dataset is a publisher of events), but creating a publisher, ultimately is a piece of code that the operator will enter in a console to make a data edit.  

More information on the process overall is available in #164 

You should check out #165, because you'll need to make equivalent changes (especially to cities.geojson) to enable any Orlando dataset to be published.

**Comment by flyinactor91** [comment]
The orlando-dev folder is just a place to keep the things we are working on separate from the rest. Any json files were for reference.
The files in intermediary will eventually be the API that converts the events from the Orlando open data source into a format that is Citygram compliant. The data sources will eventually point to something like citygram-orl-api.azureapis.net like San Fran's points to citygram-sf-registries.herokuapp.com
Thanks for the links. They're just what we needed.

**Comment by bigfleet** [comment]
@flyinactor91 Awesome!  Feel free to ping me in this thread if you need anything else.

**Comment by flyinactor91** [comment]
@bigfleet We finally have a good data source to get going. I'm trying to setup a testing server on a clean 15.10 and running into some missing items in the install documentation.

The first thing I found was that a JS runtime needed to be installed. I opted for node.js, but any listed at https://github.com/rails/execjs are said to work.

After that, the rake command is failing at the database setup. I put the user credentials I made in the .env file, but it is trying to use the vm user.
`** Invoke db:create (first_time)`
`** Execute db:create`
`createdb: database creation failed: ERROR:  permission denied to create database`
`** Invoke db:migrate (first_time)`
`** Execute db:migrate`
`rake aborted!`
I don't see anything addressing this in the docs either.
