### ISSUE TITLE
Support regional coverage

### ISSUE THREAD

**Issue by rcampbellnc** [codeforamerica/citygram#208]
The update that allows for a Triangle instance (meant to allow Durham, NC, Raleigh, NC and Cary, NC addresses) is finding only Raleigh addresses. A fix was pulled in to allow for a regional setup, but the only street addresses being found are located in Raleigh. There is data for 3 cities in this region.

**Comment by bigfleet** [comment]
**Expected behavior:**

On [the Triangle page](https://www.citygram.org/triangle) (and any future regions), the 2. What's Your Address section should have the address 'row' expanded to three columns.  The center column should be a drop-down of localities, similar otherwise in style to the radius selection.

The locality selected in the dropdown should be used in any front-end mapping behavior.

**Supported structural changes:**

We can add regional indication/support to cities.geojson in order both to activate the regional capabilities, and to indicate which localities should be exposed in the dropdowns.  The first entry in the JSON can be considered the default locality implicitly.

Ideally this regional indication will not be required for the other cities in that file.

**Comment by bigfleet** [comment]
@beetz12 Want to take a look at this?

**Comment by beetz12** [comment]
@bigfleet I've added the localities dropdown and created the following [PR](https://github.com/codeforamerica/citygram/pull/217)
Please review and let me know... thanks

**Comment by rcampbellnc** [comment]
Any thoughts about implementing ??

On Saturday, October 17, 2015, beetz12 <notifications@github.com> wrote:

> @bigfleet <https://github.com/bigfleet> I've added the localities
> dropdown and created the following PR
> <https://github.com/codeforamerica/citygram/pull/217>
> Please review and let me know... thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/citygram/issues/208#issuecomment-148955481>
> .
>


-- 
Sent from my U.S. Robotics Pilot 5000

**Comment by bigfleet** [comment]
@rcampbellnc I still have about 60% of the work to do, and there's a few high profile items in front of it for our organization.  We'll get there!  Any Rubyist with some Sinatra familiarity might be able to complete it in a work session.

**Comment by rcampbellnc** [comment]
Thanks @bigfleet!! Your work is very much appreciated! I'll put the call
out here for a Rubyist with Sinatra experience and see what we can do to
help you out!


On Sun, Oct 25, 2015 at 9:03 AM, Jim Van Fleet <notifications@github.com>
wrote:

> @rcampbellnc <https://github.com/rcampbellnc> I still have about 60% of
> the work to do, and there's a few high profile items in front of it for our
> organization. We'll get there! Any Rubyist with some Sinatra familiarity
> might be able to complete it in a work session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/citygram/issues/208#issuecomment-150920895>
> .
>



-- 
Sent from my U.S. Robotics Pilot 5000

**Comment by rcampbellnc** [comment]
@bigfleet - We've found someone to help - @bbeatonick is some we'd like to connect with you.
